#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
# https://mds.sk87.top/config-newuser
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
set -euo pipefail
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
if ! command -v curl >/dev/null 2>&1; then
    apt-get update -qq && apt-get install -y curl >/dev/null
fi
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
if [[ "${DEB_LIB_STATUS:-}" != "loaded" ]] || ! declare -f color_text >/dev/null 2>&1; then
    if source <(curl -sLf https://mds.sk87.top/lib); then
        export DEB_LIB_STATUS="loaded"
    else
        echo -e "ERROR: not loaded lib" >&2
        exit 1
    fi
fi
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
module_init "config-newuser" "$GREEN"
check_update
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

install_pkg "sudo"

# 1.[CONFIG-NEWUSER] Create user
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> create user..."
input_step "Insert name new user" "USERNAME" "ANY" || exit 0

if id "$USERNAME" &>/dev/null; then
    color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> User '$USERNAME' already exists."
else
    # === Insert password ===
    input_step "Password for $USERNAME" "PASSWORD" "PASS" || exit 0
    input_step "Repeat password" "PASSWORD2" "PASS" || exit 0

    if [ "$PASSWORD" != "$PASSWORD2" ]; then
        color_text "$RED" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> [!] Passwords do not match. Aborting."
        exit 1
    fi

    # === Create user ===
    color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> Create user $USERNAME..."
    useradd -m -s /bin/bash "$USERNAME"
    echo "$USERNAME:$PASSWORD" | chpasswd
    color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> User $USERNAME created"
fi

# 2.[CONFIG-NEWUSER] Add USERNAME to group sudo
usermod -aG sudo "$USERNAME"
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER][✓] ->->-> User $USERNAME added to sudo group"