#!/bin/bash
# https://mds.sk87.top/config
set -euo pipefail
#-#-#-#-#-#-#-#-#-#
if ! command -v curl >/dev/null 2>&1; then
    apt-get update -qq && apt-get install -y curl >/dev/null
fi
#-#-#-#-#-#-#-#-#-#
if [[ "${DEB_LIB_STATUS:-}" != "loaded" ]]; then
    if source <(curl -sLf https://mds.sk87.top/lib); then
        export DEB_LIB_STATUS="loaded"
        export COLOR_SCRIPT=$AQUA
        color_text "$COLOR_SCRIPT" "[✓] lib LOADED"
    else
        echo -e "ERROR: not loaded lib" >&2
        exit 1
    fi
else
    export COLOR_SCRIPT=$AQUA
fi
#-#-#-#-#-#-#-#-#-#
require_root
source /etc/os-release
#-#-#-#-#-#-#-#-#-#
RAW_NAME="top-sk87-mds"
setup_session $RAW_NAME
tput smcup 2>/dev/null || true
clear
tput civis 2>/dev/null || true
trap cleanup_tui EXIT
#-#-#-#-#-#-#-#-#-#
color_text "$COLOR_SCRIPT" "[✓] Session context initialized: $SESSION_DIR"
upgrade_system

# --- WRAPPER LOGIC ---
BASE_URL="https://mds.sk87.top"

MENU_ITEMS=(
  "Install netsoft              | config-netsoft"
  "Config network (Static/DHCP) | config-network"
  "Config SSH Hardening         | config-ssh"
  "Add Sudo User                | config-newuser"
  "Config NFTABLES              | config-nftables"
)

show_menu "${MENU_ITEMS[@]}" "$BASE_URL"
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#